const state={articles:[],filter:"Všetky témy",query:""};
const SUPABASE_PUBLIC_URL="https://bkyappgttwjxakkwycub.supabase.co";
const SUPABASE_PUBLIC_KEY="sb_publishable_xgl_GnkeKPFDCtyr1RtnnA_f6aaPdS4";
const FOX_IMAGE="https://commons.wikimedia.org/wiki/Special:Redirect/file/Vulpes%20vulpes%20standing.jpg?width=1600";
const escapeHtml=v=>String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]));
const normalize=v=>String(v??"").toLocaleLowerCase("sk").normalize("NFD").replace(/[\u0300-\u036f]/g,"");
function dbRowToArticle(row){return{id:row.id,category:row.category||"Slovensko",title:row.title||"Bez názvu",summary:row.intro||"",verified:row.updated_at?String(row.updated_at).slice(0,10):"",url:"clanok.html?id="+encodeURIComponent(row.id),archived:false,image:row.image_url||"",imageAlt:row.title||""}}
async function loadPublishedDrafts(){try{const r=await fetch(SUPABASE_PUBLIC_URL+"/rest/v1/drafts?state=eq.published&select=*&order=updated_at.desc",{headers:{apikey:SUPABASE_PUBLIC_KEY,Authorization:"Bearer "+SUPABASE_PUBLIC_KEY},cache:"no-store"});if(!r.ok)throw new Error("Supabase "+r.status);const rows=await r.json();return Array.isArray(rows)?rows.map(dbRowToArticle):[]}catch(e){console.warn("Supabase články sa nepodarilo načítať",e);return[]}}
const categoryOrder=["Všetky témy","Peniaze domácností","Spotrebiteľ a peniaze","Život v regiónoch","Úrady a služby","Šport","Práca a peniaze","Bezpečne na internete","Rodina a dávky"];
function cardTemplate(a){const image=a.image?`<img class="article-visual" src="${escapeHtml(a.image)}" alt="${escapeHtml(a.imageAlt||a.title)}" loading="lazy" decoding="async"><span class="article-photo-label">Ilustračná fotografia</span>`:`<div class="article-visual article-visual-placeholder" aria-hidden="true"></div>`;return`<article class="article-card"><a class="article-image-wrap" href="${escapeHtml(a.url)}" aria-label="${escapeHtml(a.title)}">${image}</a><div class="article-body"><span class="eyebrow">${escapeHtml(a.category)}</span><h3>${escapeHtml(a.title)}</h3><p>${escapeHtml(a.summary)}</p><div class="article-meta"><span>${a.verified?"Overené "+escapeHtml(a.verified):"Objektív24"}</span><a href="${escapeHtml(a.url)}">Čítať ďalej →</a></div></div></article>`}
function archiveTemplate(a){return`<article class="archive-card"><span class="eyebrow">${escapeHtml(a.category)}</span><h3>${escapeHtml(a.title)}</h3><a href="${escapeHtml(a.url)}">Otvoriť článok →</a></article>`}
function renderFilters(){const root=document.querySelector("#filters");if(!root)return;root.innerHTML=categoryOrder.map(c=>`<button class="filter-button ${state.filter===c?"is-active":""}" type="button" data-filter="${escapeHtml(c)}">${escapeHtml(c)}</button>`).join("");root.querySelectorAll("[data-filter]").forEach(b=>b.addEventListener("click",()=>{state.filter=b.dataset.filter;renderFilters();renderArticles()}))}
function renderArticles(){const grid=document.querySelector("#articles-grid"),archive=document.querySelector("#archive-grid"),empty=document.querySelector("#empty-state");if(!grid||!archive||!empty)return;const q=normalize(state.query.trim()),active=state.articles.filter(a=>!a.archived),filtered=active.filter(a=>(state.filter==="Všetky témy"||a.category===state.filter)&&(!q||normalize([a.title,a.summary,a.category].join(" ")).includes(q)));grid.innerHTML=filtered.map(cardTemplate).join("");empty.hidden=filtered.length!==0;archive.innerHTML=state.articles.filter(a=>a.archived).map(archiveTemplate).join("");document.querySelector("#issued-count")&&(document.querySelector("#issued-count").textContent=state.articles.length);document.querySelector("#active-count")&&(document.querySelector("#active-count").textContent=`Aktuálne: ${active.length}`)}
async function loadArticles(){try{const r=await fetch("data/articles.json",{cache:"no-store"});if(!r.ok)throw new Error("articles.json");const staticArticles=await r.json();staticArticles.forEach(a=>{if(a.slug==="vakcinacia-lisok"){a.image=FOX_IMAGE;a.imageAlt="Celá líška hrdzavá stojaca vo voľnej prírode";a.imageLicense="Wikimedia Commons · Public domain · U.S. Fish and Wildlife Service"}});const live=await loadPublishedDrafts(),titles=new Set(live.map(x=>normalize(x.title)));state.articles=[...live,...staticArticles.filter(x=>!titles.has(normalize(x.title)))];renderFilters();renderArticles()}catch(e){console.error(e);document.querySelector("#articles-grid").innerHTML="<p>Články sa nepodarilo načítať. Skúste stránku obnoviť.</p>"}}
document.querySelector(".menu-button")?.addEventListener("click",e=>{const nav=document.querySelector("#site-nav"),open=nav.classList.toggle("is-open");e.currentTarget.setAttribute("aria-expanded",String(open))});
document.querySelector("#search-form")?.addEventListener("submit",e=>{e.preventDefault();state.query=document.querySelector("#search-input")?.value||"";renderArticles()});document.querySelector("#search-input")?.addEventListener("input",e=>{state.query=e.currentTarget.value;renderArticles()});document.querySelector("#reset-search")?.addEventListener("click",()=>{state.filter="Všetky témy";state.query="";const i=document.querySelector("#search-input");if(i)i.value="";renderFilters();renderArticles()});
const revealEls=[...document.querySelectorAll(".reveal")];
if(window.matchMedia("(max-width: 680px)").matches){revealEls.forEach(el=>el.classList.add("is-visible"))}else{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.05,rootMargin:"0px 0px 120px 0px"});revealEls.forEach(el=>observer.observe(el))}
loadArticles();