const STORAGE_KEY="objektiv24-redakcia-drafts-v1";const $=s=>document.querySelector(s);let drafts=[],currentImageData="";
function nowDate(){return new Intl.DateTimeFormat("sk-SK",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date())}
function loadLocalDrafts(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]")}catch{return[]}}
function saveLocalDrafts(){localStorage.setItem(STORAGE_KEY,JSON.stringify(drafts.filter(d=>!d.seed)))}
async function seedPublishedArticles(){try{const r=await fetch("data/articles.json",{cache:"no-store"});const a=await r.json();return a.map(x=>({id:"published-"+x.slug,seed:true,title:x.title,category:x.category,intro:x.summary,state:x.archived?"archived":"published",updated:x.verified,whatHappened:"",whatItMeans:"",nextStep:"",sources:x.url||"",image:x.image||"",imageName:""}))}catch{return[]}}
function renderDraftList(){const q=($("#draft-search").value||"").toLocaleLowerCase("sk");const v=drafts.filter(d=>(d.title||"Bez názvu").toLocaleLowerCase("sk").includes(q));$("#draft-count").textContent=drafts.length;$("#draft-list").innerHTML=v.map(d=>`<button type="button" class="draft-card ${$("#draft-id").value===d.id?"is-active":""}" data-id="${d.id}"><span class="badge">${d.state==="published"?"VYDANÝ":d.state==="archived"?"ARCHÍV":"NÁVRH"} · upraviteľný návrh</span><h3>${d.title||"Bez názvu"}</h3><time>${d.updated||""}</time></button>`).join("");document.querySelectorAll(".draft-card").forEach(b=>b.addEventListener("click",()=>selectDraft(b.dataset.id)))}
function resetForm(){$("#article-form").reset();$("#draft-id").value="";$("#category").value="Slovensko v súvislostiach";$("#draft-status").textContent="Nový návrh";currentImageData="";hidePreview();renderDraftList()}
function selectDraft(id){const d=drafts.find(x=>x.id===id);if(!d)return;$("#draft-id").value=d.id;$("#title").value=d.title||"";$("#category").value=d.category||"";$("#intro").value=d.intro||"";$("#what-happened").value=d.whatHappened||"";$("#what-it-means").value=d.whatItMeans||"";$("#next-step").value=d.nextStep||"";$("#sources").value=d.sources||"";$("#state").value=d.state||"draft";$("#draft-status").textContent=d.state==="published"?"Vydaný článok":d.state==="archived"?"Archív":"Uložený návrh";currentImageData=d.image||"";currentImageData?showPreview(currentImageData):hidePreview();renderDraftList();window.scrollTo({top:0,behavior:"smooth"})}
function readForm(){const id=$("#draft-id").value;return{id:id||"draft-"+Date.now(),seed:false,title:$("#title").value.trim(),category:$("#category").value.trim(),intro:$("#intro").value.trim(),whatHappened:$("#what-happened").value.trim(),whatItMeans:$("#what-it-means").value.trim(),nextStep:$("#next-step").value.trim(),sources:$("#sources").value.trim(),state:$("#state").value,updated:nowDate(),image:currentImageData,imageName:$("#image-upload").files?.[0]?.name||""}}
function showPreview(src){const r=$("#image-preview");r.hidden=false;r.querySelector("img").src=src}function hidePreview(){const r=$("#image-preview");r.hidden=true;r.querySelector("img").removeAttribute("src")}
$("#article-form").addEventListener("submit",e=>{e.preventDefault();const d=readForm();if(!d.title)return;const i=drafts.findIndex(x=>x.id===d.id);if(i>=0&&drafts[i].seed){d.id="draft-"+Date.now();drafts.unshift(d)}else if(i>=0)drafts[i]=d;else drafts.unshift(d);saveLocalDrafts();$("#draft-id").value=d.id;$("#draft-status").textContent="Uložený návrh";renderDraftList()});
$("#new-draft").addEventListener("click",resetForm);$("#draft-search").addEventListener("input",renderDraftList);
$("#image-upload").addEventListener("change",e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{currentImageData=String(r.result||"");showPreview(currentImageData)};r.readAsDataURL(f)});
$("#remove-image").addEventListener("click",()=>{currentImageData="";$("#image-upload").value="";hidePreview()});
$("#export-draft").addEventListener("click",()=>{const d=readForm(),b=new Blob([JSON.stringify(d,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=(d.title||"objektiv24-navrh").toLocaleLowerCase("sk").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")+".json";a.click();URL.revokeObjectURL(u)});
(async()=>{const [seed,local]=await Promise.all([seedPublishedArticles(),Promise.resolve(loadLocalDrafts())]);drafts=[...local,...seed];renderDraftList();resetForm()})();